### ISSUE TITLE
Incorrect assignment of limb_type_vec in environment modules

### ISSUE THREAD

**Issue by sunghoonhong** [huangwl18/modular-rl#13]
Hello Wenlong,
Thanks for sharing your interesting work!

I have run some experiments with your code, but I think there are some typo in ```_get_obs_per_limb()``` in environment .py files.
Specifically, for humanoid++, the ```limb_type_vec``` is assigned incorrectly, i.e. every limbs are assigned to ```(0, 0, 0, 0)```.

In humanoid xmls, the name of limb ```body``` belongs to {'torso', '(left/right) shoulder', '(left/right) thigh', '(left/right) shin', '(left/right) upper arm', '(left/right) lower arm'}, but the limb type assignment condition compares the name with {'hip', 'knee', 'shoulder', 'elbow'} which are the names of ```motor (joint)``` in your code.

I'm wondering if this is intended and would like to hear from you if this makes some difference in model performance.

Thank you

**Comment by huangwl18** [comment]
Thanks for the interest in the paper!

This is a legacy code borrowed from the `walker` environments, and based on our brief experimentations, including it or not doesn't seem to make a big difference.

**Comment by sunghoonhong** [comment]
Thanks for your comment.

Are the experiments in the paper conducted on correct limb_type, using other code than this legacy code?

And what does ```walker``` environments mean?
Just ```walker++``` environments such as ```walker_2_main.py``` or ```walker_3_main.py```?
I'm confusing since ```limb_type``` assignment in ```walker++``` is still correct, while ```humanoid++``` code is incorrect.

Anyway, in conclusion, it does not affect the results that much?

**Comment by huangwl18** [comment]
Sorry for the super late reply and thanks for spotting that! Fixing this might slightly improve the performance. However, from my earlier experience, this shouldn't affect the performance a lot.
