### ISSUE TITLE
Difference with and without torchfold? (Question)

### ISSUE THREAD

**Issue by olivierp9** [huangwl18/modular-rl#3]
What is the advantage of using torchfold for trainning?

**Comment by huangwl18** [comment]
Torchfold is a dynamical batching package, which can help speed up inference if two nodes are not dependent. You may find this blog post from the author helpful: http://near.ai/articles/2017-09-06-PyTorch-Dynamic-Batching/

**Comment by olivierp9** [comment]
Thank you!
