### ISSUE TITLE
Have you tried this method to train the standard 3d humanoid?

### ISSUE THREAD

**Issue by han-x** [huangwl18/modular-rl#5]
How many steps does it take to train a 3D model in this way? Your idea is very innovative, and I want to use this to improve my policy.

**Comment by huangwl18** [comment]
Thanks for the interest in the paper!

We didn't try to train the policy on a 3d humanoid as most of the Gym MuJoCo locomotion agents are in 2d and the goal is to investigate the possibility of training a single policy for multiple agent morphologies. However, it is expected to work well in 3d too, but one might need to modify the dimensionality of input/output correspondingly.
