### ISSUE TITLE
List of training/test environments

### ISSUE THREAD

**Issue by yobibyte** [huangwl18/modular-rl#7]
Hi @huangwl18, @pathak22! Thanks for the code release.

The paper does not specify which environments were used for training and for zero-shot evaluation. For instance, Humanoid++ has 8 environments out of which the two were used for zero-shot evaluation. Can you tell me which?

Can you, please, provide the full list for all of the environments used in the paper?

**Comment by huangwl18** [comment]
Thanks for the interest in the paper! 

For the results reported in the paper, the following agents are in the held-out set for the corresponding experiments:
- Walker++: walker_5_main, walker_6_flipped
- Humanoid++: humanoid_2d_7_right_arm, humanoid_2d_7_lower_arms
- Cheetah++: cheetah_4_front, cheetah_5_balanced, cheetah_6_front
- Walker-Hopper++: walker_5_main, walker_6_flipped, hopper_3
- Walker-Hopper-Humanoid++: walker_5_main, walker_6_flipped, hopper_3, humanoid_2d_7_right_arm, humanoid_2d_7_lower_arms

All other agents in the corresponding experiments are used for training.

**Comment by yobibyte** [comment]
Thank you!
